rareDb = {
    ["Alterac Mountains"] = {
        ["Araga"] = {
            -- ["reynolds"] = {1 = 1706618285}, -- reynolds sees it alive
            -- ["wooshie"] = {2 = 1706618290}, -- wooshie kills it
            -- ["stoneharry"] = {0 = 1706618295}, -- stoneharry finds it dead
        },
        ["Cranky Benj"] = {},
        ["Gravis Slipknot"] = {},
        ["Jimmy the Bleeder"] = {},
        ["Lo'Grosh"] = {},
        ["Skhowl"] = {},
        ["Stone Fury"] = {},
        ["Narillasanz"] = {},
    },
    ["Arathi Highlands"] = {
        ["Foulbelly"] = {},
        ["Geomancer Flintdagger"] = {},
        ["Kovork"] = {},
        ["Molok the Crusher"] = {},
        ["Montrose"] = {},
        ["Nimar the Slayer"] = {},
        ["Prince Nazjak"] = {},
        ["Ruul Onestone"] = {},
        ["Singer"] = {},
        ["Zalas Witherbark"] = {},
    },
    ["Ashenvale"] = {
        ["Akkrilus"] = {},
        ["Apothecary Falthis"] = {},
        ["Branch Snapper"] = {},
        ["Eck'alom"] = {},
        ["Lady Vespia"] = {},
        ["Mist Howler"] = {},
        ["Mugglefin"] = {},
        ["Oakpaw"] = {},
        ["Prince Raze"] = {},
        ["Rorgish Jowl"] = {},
        ["Terrowulf Packlord"] = {},
        ["Ursol'lok"] = {},
        ["Wandering Protector"] = {},
        ["Wrathtail Tide Princess"] = {},
    },
    ["Azshara"] = {
        ["Antilos"] = {},
        ["Bone Witch"] = {},
        ["Gatekeeper Rageroar"] = {},
        ["General Fangferror"] = {},
        ["Lady Sesspira"] = {},
        ["Magister Hawkhelm"] = {},
        ["Master Feardred"] = {},
        ["Monnos the Elder"] = {},
        ["Scalebeard"] = {},
        ["Spirit of the Damned"] = {},
        ["The Evalcharr"] = {},
        ["Varo'then's Ghost"] = {},
    },
    ["Badlands"] = {
        ["7:XT"] = {},
        ["Anathemus"] = {},
        ["Broken Tooth"] = {},
        ["Rumbler"] = {},
        ["Shadowforge Commander"] = {},
        ["Siege Golem"] = {},
        ["War Golem"] = {},
        ["Zaricotl"] = {},
        ["The Tombkeeper"] = {},
        ["Digmaster Shovelphlange"] = {},
    },
    ["Blackrock Depths"] = {
        ["Panzor the Invincible"] = {},
        ["Pyromancer Loregrain"] = {},
    },
    ["Blackrock Mountain"] = {
        ["The Behemoth"] = {},
    },
    ["Blackrock Spire"] = {
        ["Bannok Grimaxe"] = {},
        ["Burning Felguard"] = {},
        ["Crystal Fang"] = {},
        ["Ghok Bashguud"] = {},
        ["Jed Runewatcher"] = {},
        ["Quartermaster Zigris"] = {},
        ["Spirestone Battle Lord"] = {},
        ["Spirestone Butcher"] = {},
        ["Spirestone Lord Magus"] = {},
        ["Urok Doomhowl"] = {},
    },
    ["Blasted Lands"] = {
        ["Akubar the Seer"] = {},
        ["Clack the Reaver"] = {},
        ["Deatheye"] = {},
        ["Dreadscorn"] = {},
        ["Grunter"] = {},
        ["Magronos the Unyielding"] = {},
        ["Mojo the Twisted"] = {},
        ["Ravage"] = {},
        ["Spiteflayer"] = {},
        ["Bone Witch"] = {},
        ["Spirit of the Damned"] = {},
        ["Hellion"] = {},
    },
    ["Burning Steppes"] = {
        ["Bone Witch"] = {},
        ["Deathmaw"] = {},
        ["Gorgon'och"] = {},
        ["Gruklash"] = {},
        ["Hahk'Zor"] = {},
        ["Hematos"] = {},
        ["Malfunctioning Reaver"] = {},
        ["Spirit of the Damned"] = {},
        ["Terrorspark"] = {},
        ["Thauris Balgarr"] = {},
        ["Volchan"] = {},
        ["Battlecaller Ror"] = {},
    },
    ["Darkshore"] = {
        ["Carnivous the Breaker"] = {},
        ["Firecaller Radison"] = {},
        ["Flagglemurk the Cruel"] = {},
        ["Lady Moongazer"] = {},
        ["Lady Vespira"] = {},
        ["Licillin"] = {},
        ["Lord Sinslayer"] = {},
        ["Shadowclaw"] = {},
        ["Strider Clutchmother"] = {},
        ["Ancient Guardian"] = {},
    },
    ["Deadwind Pass"] = {
        ["Duke Ragereaver"] = {},
    },
    ["Desolace"] = {
        ["Accursed Slitherblade"] = {},
        ["Cursed Centaur"] = {},
        ["Giggler"] = {},
        ["Hissperak"] = {},
        ["Kaskk"] = {},
        ["Prince Kellen"] = {},
        ["Dreadwhisper"] = {},
        ["Wep"] = {},
        ["Yor"] = {},
        ["Staggon"] = {},
        ["Tepolar"] = {},
        ["Grok Painweaver"] = {},
    },
    ["Dire Maul"] = {
        ["Mushgog"] = {},
        ["Skarr the Unbreakable"] = {},
        ["The Razza"] = {},
    },
    ["Dun Morogh"] = {
        ["Ben"] = {},
        ["Bjarn"] = {},
        ["Edan the Howler"] = {},
        ["Gibblewilt"] = {},
        ["Great Father Arctikus"] = {},
        ["Hammerspine"] = {},
        ["Timber"] = {},
    },
    ["Durotar"] = {
        ["Captain Flat Tusk"] = {},
        ["Death Flayer"] = {},
        ["Felweaver Scornn"] = {},
        ["Geolord Mottle"] = {},
        ["Warlord Kolkanis"] = {},
        ["Watch Commander Zalaphil"] = {},
    },
    ["Duskwood"] = {
        ["Lord Malathrom"] = {},
        ["Lupos"] = {},
        ["Lurking Shadow"] = {},
        ["Mor'Ladim"] = {},
        ["Naraxis"] = {},
        ["Nefaru"] = {},
        ["Stitches"] = {},
        ["Kern the Enforcer"] = {},
        ["Defias Lookout"] = {},
        ["Suffering"] = {},
        ["Tilloa"] = {},
        ["Vladimir"] = {},
    },
    ["Dustwallow Marsh"] = {
        ["Brimgore"] = {},
        ["Burgle Eye"] = {},
        ["Coral Shark"] = {},
        ["Darkmist Widow"] = {},
        ["Dart"] = {},
        ["Drogoth the Roamer"] = {},
        ["Hayoc"] = {},
        ["Lord Angler"] = {},
        ["Oozeworm"] = {},
        ["Ripscale"] = {},
        ["The Rot"] = {},
    },
    ["Eastern Plaguelands"] = {
        ["Bone Witch"] = {},
        ["Deathspeaker Selendre"] = {},
        ["Duggan Wildhammer"] = {},
        ["Gish the Unmoving"] = {},
        ["Hed'mush the Rotting"] = {},
        ["High General Abbendis"] = {},
        ["Lord Darkscythe"] = {},
        ["Ranger Lord Hawkspear"] = {},
        ["Spirit of the Damned"] = {},
        ["Warlord Thresh'jin"] = {},
        ["Zul'Brin Warpbranch"] = {},
        ["Deathcaller Majestis"] = {},
        ["Ushalac the Gloomdweller"] = {},
        ["Gash'nak the Cannibal"] = {},
    },
    ["Elwynn Forest"] = {
        ["Fedfennel"] = {},
        ["Gruff Swiftbite"] = {},
        ["Morgaine the Sly"] = {},
        ["Mother Fang"] = {},
        ["Narg the Taskmaster"] = {},
        ["Thuros Lightfingers"] = {},
    },
    ["Felwood"] = {
        ["Alshirr Banebreath"] = {},
        ["Death Howl"] = {},
        ["Dessecus"] = {},
        ["Immolatus"] = {},
        ["Mongress"] = {},
        ["Olm the Wise"] = {},
        ["Ragepaw"] = {},
        ["The Ongar"] = {},
    },
    ["Feralas"] = {
        ["Antilus the Soarer"] = {},
        ["Arash-ethis"] = {},
        ["Bloodroar the Stalker"] = {},
        ["Diamond Head"] = {},
        ["Gnarl Leafbrother"] = {},
        ["Grug'thok the Seer"] = {},
        ["Lady Szallah"] = {},
        ["Mushgog"] = {},
        ["Old Grizzlegut"] = {},
        ["Qirot"] = {},
        ["Skarr the Unbreakable"] = {},
        ["Snarler"] = {},
        ["The Razza"] = {},
        ["Dreamwatcher Forktongue"] = {},
    },
    ["Gnomeregan"] = {
        ["Dark Iron Ambassador"] = {},
    },
    ["Hillsbrad Foothills"] = {
        ["Big Samras"] = {},
        ["Creepthess"] = {},
        ["Lady Zephris"] = {},
        ["Narillasanz"] = {},
        ["Ro'Bark"] = {},
        ["Scargil"] = {},
        ["Tamra Stormpike"] = {},
        ["Tamara Stormpike"] = {},
    },
    ["Ironforge"] = {
        ["Spectral Stalker"] = {},
    },
    ["Loch Modan"] = {
        ["Boss Galgosh"] = {},
        ["Digmaster Shovelphlange"] = {},
        ["Emogg the Crusher"] = {},
        ["Gradok"] = {},
        ["Grizlak"] = {},
        ["Haren Swifthoof"] = {},
        ["Large Loch Crocolisk"] = {},
        ["Lord Condar"] = {},
        ["Magosh"] = {},
        ["Ol' Sooty"] = {},
        ["Shanda the Spinner"] = {},
        ["Thragomm"] = {},
    },
    ["Maraudon"] = {
        ["Meshlok the Harvester"] = {},
    },
    ["Mulgore"] = {
        ["Enforcer Emilgund"] = {},
        ["Ghost Howl"] = {},
        ["Mazzranache"] = {},
        ["Sister Hatelash"] = {},
        ["Snagglespear"] = {},
        ["The Rake"] = {},
    },
    ["Razorfen Kraul"] = {
        ["Blind Hunter"] = {},
        ["Earthcaller Halmgar"] = {},
        ["Razorfen Spearhide"] = {},
    },
    ["Razorfen Downs"] = {
        ["Kelemis the Lifeless"] = {}, 
    },
    ["Redridge Mountains"] = {
        ["Boulderheart"] = {},
        ["Chatter"] = {},
        ["Kazon"] = {},
        ["Lurking Shadow"] = {},
        ["Ribchaser"] = {},
        ["Rohh the Silent"] = {},
        ["Seeker Aqualon"] = {},
        ["Snarlflare"] = {},
        ["Squiddic"] = {},
        ["Volchan"] = {},
    },
    ["Scarlet Monastery"] = {
        ["Azshir the Sleepless"] = {},
        ["Fallen Champion"] = {},
        ["Ironspine"] = {},
    },
    ["Searing Gorge"] = {
        ["Faulty War Golem"] = {},
        ["Highlord Mastrogonde"] = {},
        ["Rekk'tilac"] = {},
        ["Scald"] = {},
        ["Shleipnarr"] = {},
        ["Slave Master Blackheart"] = {},
        ["Smoldar"] = {},
        ["The Behemoth"] = {},
        ["Dark Iron Enforcer"] = {},
    },
    ["Shadowfang Keep"] = {        
        ["Deathsworn Captain"] = {},
    },
    ["Silithus"] = {
        ["Gretheer"] = {},
        ["Grubthor"] = {},
        ["Huricanian"] = {},
        ["Krellack"] = {},
        ["Lapress"] = {},
        ["Rex Ashil"] = {},
        ["Setis"] = {},
        ["Twilight Lord Everun"] = {},
        ["Zora"] = {},
        ["Spawn of Ouro"] = {},
    },
    ["Silverpine Forest"] = {
        ["Dalaran Spellscribe"] = {},
        ["Gorefang"] = {},
        ["Krethis Shadowspinner"] = {},
        ["Old Vicejaw"] = {},
        ["Ravenclaw Regent"] = {},
        ["Rot Hide Bruiser"] = {},
        ["Snarlmane"] = {},
        ["Son of Arugal"] = {},
    },
    ["Stonetalon Mountains"] = {
        ["Brother Ravenoak"] = {},
        ["Foreman Rigger"] = {},
        ["Nal'taszar"] = {},
        ["Pridewing Patriarch"] = {},
        ["Sentinel Amarassan"] = {},
        ["Sister Riven"] = {},
        ["Sorrow Wing"] = {},
        ["Taskmaster Whipfang"] = {},
        ["Vengeful Ancient"] = {},
    },
    ["Stormwind City"] = {
        ["Sewer Beast"] = {},
    },
    ["Stranglethorn Vale"] = {
        ["Gluggle"] = {},
        ["Kurmokk"] = {},
        ["Lord Sakrasis"] = {},
        ["Mosh'Ogg Butcher"] = {},
        ["Rippa"] = {},
        ["Roloch"] = {},
        ["Scale Belly"] = {},
        ["Scarshield Quartermaster"] = {},
        ["Verifonix"] = {},
    },
    ["Stratholme"] = {
        ["Hearthsinger Forresten"] = {},
        ["Skul"] = {},
        ["Stonespine"] = {},
        ["Timmy the Cruel"] = {},
    },
    ["Swamp of Sorrows"] = {
        ["Fingat"] = {},
        ["Gilmorian"] = {},
        ["Jade"] = {},
        ["Lord Captain Wyrmak"] = {},
        ["Lost One Chieftain"] = {},
        ["Lost One Cook"] = {},
        ["Molt Thorn"] = {},
        ["Zekkis"] = {},
    },
    ["Tanaris"] = {
        ["Bone Witch"] = {},
        ["Cyclok the Mad"] = {},
        ["Greater Firebird"] = {},
        ["Haarka the Ravenous"] = {},
        ["Jin'Zallah the Sandbringer"] = {},
        ["Kregg Keelhaul"] = {},
        ["Murderous Blisterpaw"] = {},
        ["Omgorn the Lost"] = {},
        ["Soriid the Devourer"] = {},
        ["Spirit of the Damned"] = {},
        ["Warleader Krazzilak"] = {},
        ["Soul of Tanaris"] = {},
    },
    ["Teldrassil"] = {
        ["Blackmoss the Fetid"] = {},
        ["Duskstalker"] = {},
        ["Fury Shelda"] = {},
        ["Grimmaw"] = {},
        ["Threggil"] = {},
        ["Uruson"] = {},
    },
    ["Temple of Atal'Hakkar"] = {
        ["Veyzhak the Cannibal"] = {},
        ["Zekkis"] = {},
        ["Jade"] = {},
    },
    ["The Barrens"] = {
        ["Ambassador Bloodrage"] = {},
        ["Azzere the Skyblade"] = {},
        ["Boahn"] = {},
        ["Brokespear"] = {},
        ["Brontus"] = {},
        ["Captain Gerogg Hammertoe"] = {},
        ["Digger Flameforge"] = {},
        ["Dishu"] = {},
        ["Elder Mystic Razorsnout"] = {},
        ["Engineer Whirleygig"] = {},
        ["Foreman Grills"] = {},
        ["Geopriest Gukk'rok"] = {},
        ["Gesharahan"] = {},
        ["Hagg Taurenbane"] = {},
        ["Heggin Stonewhisker"] = {},
        ["Humar the Pridelord"] = {},
        ["Malgin Barleybrew"] = {},
        ["Rathorian"] = {},
        ["Rocklance"] = {},
        ["Silithid Harvester"] = {},
        ["Sister Rathtalon"] = {},
        ["Sludge Beast"] = {},
        ["Snort the Heckler"] = {},
        ["Stonearm"] = {},
        ["Swiftmane"] = {},
        ["Swinegart Spearhide"] = {},
        ["Takk the Leaper"] = {},
        ["Thunderstomp"] = {},
        ["Kolkar Observer"] = {},
        ["Trigore the Lasher"] = {},
    },
    ["The Deadmines"] = {
        ["Miner Johnson"] = {},
        ["Capo the Mean"] = {},
        ["Marisa du'Paige"] = {},
        ["Brainwashed Noble"] = {},
    },
    ["The Hinterlands"] = {
        ["Grimungous"] = {},
        ["Ironback"] = {},
        ["Jalinde Summerdrake"] = {},
        ["Mith'rethis the Enchanter"] = {},
        ["Old Cliff Jumper"] = {},
        ["Razortalon"] = {},
        ["Retherokk the Berserker"] = {},
        ["The Reak"] = {},
        ["Witherheart the Stalker"] = {},
        ["Zul'arek Hatefowler"] = {},
        ["Death Knight Soulbearer"] = {},
        ["Wildhammer Ambassador"] = {},
        ["Jin'ari"] = {},
    },
    ["The Stockade"] = {
        ["Bruegal Ironknuckle"] = {},
    },
    ["The Temple of Atal'Hakkar"] = {
        ["Veyzhak the Cannibal"] = {},
    },
    ["Thousand Needles"] = {
        ["Achellios the Banished"] = {},
        ["Gibblesnik"] = {},
        ["Harb Foulmountain"] = {},
        ["Heartrazor"] = {},
        ["Ironeye the Invincible"] = {},
        ["Silithid Ravager"] = {},
        ["Steelsnap"] = {},
        ["Rok'Alim the Pounder"] = {},
        ["Vile Sting"] = {},
        ["Scillia Daggerquil"] = {},
    },
    ["Thunder Bluff"] = {
        ["Ghost Howl"] = {},
    },
    ["Tirisfal Glades"] = {
        ["Bayne"] = {},
        ["Deeb"] = {},
        ["Fallen Hero"] = {},
        ["Farmer Solliden"] = {},
        ["Fellicent's Shade"] = {},
        ["Lost Soul"] = {},
        ["Muad"] = {},
        ["Ressan the Needler"] = {},
        ["Sri'skulk"] = {},
        ["Tormented Spirit"] = {},
        ["The Zealot"] = {},
    },
    ["Uldaman"] = {
        ["Digmaster Shovelphlange"] = {},
    },
    ["Un'Goro Crater"] = {
        ["Baron Charr"] = {},
        ["Clutchmother Zavas"] = {},
        ["Gruff"] = {},
        ["King Mosh"] = {},
        ["Ravasaur Matriarch"] = {},
        ["Uhk'loc"] = {},
    },
    ["The Wailing Caverns"] = {
        ["Deviate Faerie Dragon"] = {},
        ["Trigore the Lasher"] = {},
        ["Boahn"] = {},
    },
    ["Western Plaguelands"] = {
        ["Fallen Hero"] = {},
        ["Foreman Jerris"] = {},
        ["Foreman Marcrid"] = {},
        ["Foulmane"] = {},
        ["Lord Maldazzar"] = {},
        ["Putridius"] = {},
        ["Scarlet Executioner"] = {},
        ["Scarlet High Clerist"] = {},
        ["Scarlet Interrogator"] = {},
        ["Scarlet Judge"] = {},
        ["Scarlet Smith"] = {},
        ["The Husk"] = {},
        ["Felendor the Accuser"] = {},
    },
    ["Westfall"] = {
        ["Brack"] = {},
        ["Brainwashed Noble"] = {},
        ["Carver Molsen"] = {},
        ["Foe Reaper 4000"] = {},
        ["Leprithus"] = {},
        ["Marisa du'Paige"] = {},
        ["Master Digger"] = {},
        ["Sergeant Brashclaw"] = {},
        ["Slark"] = {},
        ["Vultros"] = {},
        ["Capo the Mean"] = {},
    },
    ["Wetlands"] = {
        ["Dragonmaw Battlemaster"] = {},
        ["Garneg Charskull"] = {},
        ["Gnawbone"] = {},
        ["Leech Widow"] = {},
        ["Ma'ruk Wyrmscale"] = {},
        ["Mirelow"] = {},
        ["Razormaw Matriarch"] = {},
        ["Sludginn"] = {},
        ["Brundar"] = {},
    },
    ["Winterspring"] = {
        ["Azurous"] = {},
        ["Bone Witch"] = {},
        ["General Colbatann"] = {},
        ["Grizzle Snowpaw"] = {},
        ["Kashoch the Reaver"] = {},
        ["Lady Hederine"] = {},
        ["Mezzir the Howler"] = {},
        ["Rak'shiri"] = {},
        ["Spirit of the Damned"] = {},
        ["Berylgos"] = {},
        ["Tatterhide"] = {},
    },
    ["Zul'Farrak"] = {
        ["Dustwraith"] = {},
        ["Sandarr Dunereaver"] = {},
        ["Zerillis"] = {},
    },
}

function unitscan_zone_targets()
    local zone = GetZoneText()
    if not zone then return end

    if rareDb[zone] then
        unitscan_zonetargets = rareDb[zone]
    else
        unitscan_zonetargets = {} -- reset zonetargets
    end
end

function unitscan_add_time(zone, name, state)
    local currentUTCTime = time(date("!*t"))
    local codes = {
        [0] = "dead",
        [1] = "alive",
        [2] = "killed",
    }
    entry = {state = currentUTCTime}

    if rareDb[zone][name] then
        -- add reference table for player if none exists
        if not rareDb[zone][name][UnitName("player")] then
            rareDb[zone][name][UnitName("player")] = {}
        end

        -- if found alive or killed (not dead) clear previous dead entry
        if not state == 0 then
            rareDb[zone][name][UnitName("player")][state] = currentUTCTime
            table.remove(rareDb[zone][name][UnitName("player")], 0)
        else
            -- if found dead keep oldest entry
            if not rareDb[zone][name][UnitName("player")][0] then
                rareDb[zone][name][UnitName("player")][state] = currentUTCTime
            end
            -- wipe previous alive entry
            table.remove(rareDb[zone][name][UnitName("player")], 1)
        end
        for player, entries in pairs(rareDb[zone][name]) do
            for state, timestamp in pairs(entries) do

                print(player.." found "..name.." "..codes[state].." at "..tostring(date("%m/%d/%y %H:%M:%S",timestamp)))
            end
        end
    end
end
